# Generated by Django 5.0.3 on 2024-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('due', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
